anims = {
    {dic = "gestures@f@standing@casual", anim = "gesture_bring_it_on", label = "Dale", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_bye_hard", label = "Adios", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_come_here_hard", label = "Ven aqui", category = "Gesture", loop = 0},
    {dic = "missheist_agency3aig_24", anim = "agent01_conversation", label = "Conversacion", category = "Misc", loop = 0},
    {dic = "misscarstealfinalecar_5_ig_3", anim = "crouchloop", label = "Agacharse", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_damn", label = "Damn", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_displeased", label = "Disgustado", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_easy_now", label = "Ahora facil", category = "Gesture", loop = 0},
	{dic = "mp_sleep", anim = "sleep_introfemale", label = "Quedarse dormido", category = "Misc", loop = 50},
    {dic = "gestures@f@standing@casual", anim = "gesture_hello", label = "Hola", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "getsure_its_mine", label = "Es mio", category = "Gesture", loop = 0},
    {dic = "missfam4leadinoutmcs2", anim = "tracy_loop", label = "Arrodillarse en el suelo", category = "Misc", loop = 0},
    {dic = "mp_safehouse", anim = "lap_dance_girl", label = "Lap Dance", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_me", label = "Yo", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_head_no", label = "No", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_no_way", label = "De ninguna manera", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_pleased", label = "Satisfecho", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_point", label = "Punto", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_shrug_hard", label = "Encoger hombros", category = "Gesture", loop = 0},
    {dic = "missexile1_cargoplane", anim = "call_radio_player2", label = "Sentarse y hablar en la radio", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_what_hard", label = "Que", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_why", label = "Porque", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_nod_yes_hard", label = "Si", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_you_hard", label = "Tu", category = "Gesture", loop = 0},
    {dic = "anim@amb@business@coc@coc_packing_hi@", anim = "full_cycle_v1_pressoperator", label = "Prensa", category = "Misc", loop = 0},
    {dic = "missfam5_blackout", anim = "pass_out", label = "Desmayarse", category = "Misc", loop = 0},
    {dic = "missfbi5ig_21", anim = "holdup_hallway_saw_player_scientist", label = "Asustado", category = "Misc", loop = 0},
    {dic = "missfbi5ig_21", anim = "hand_up_scientist", label = "Manos arriba cientifico", category = "Misc", loop = 0},
    {dic = "missfbi5ig_36", anim = "_reaction_to_heli", label = "See Heli", category = "Misc", loop = 0},
    {dic = "missheist_agency3astumble_getup", anim = "stumble_getup", label = "Tropezar", category = "Misc", loop = 0},
    {dic = "missfam5_blackout", anim = "vomit", label = "Vomitar", category = "Misc", loop = 0},
    {dic = "missfam5_yoga", anim = "f_yogapose_a", label = "Yoga Pose", category = "Misc", loop = 0},
	{dic = "mp_ped_interaction", anim = "hugs_guy_a", label = "Abrazo", category = "New", loop = 0},
	{dic = "mp_player_int_upperwank", anim = "mp_player_int_wank_01", label = "Gilipollas", category = "New", loop = 0},
	{dic = "mp_arresting", anim = "idle", label = "Esposado", category = "New", loop = 0},
	{dic = "anim@mp_snowball", anim = "pickup_snowball", label = "Recoger", category = "New", loop = 0},
	{dic = "anim@mp_player_intuppernose_pick", anim = "enter", label = "Hurgarse en la nariz", category = "New", loop = 0},
	{dic = "mini@prostitutes@sexnorm_veh", anim = "bj_loop_prostitute", label = "Chupar coche", category = "New", loop = 0},
	{dic = "mini@prostitutes@sexnorm_veh", anim = "bj_loop_male", label = "Recibir coche", category = "New", loop = 0},

	{dic = "rcmpaparazzo_2", anim = "shag_loop_poppy", label = "Sexo ser pasivo", category = "New", loop = 0},
	{dic = "rcmpaparazzo_2", anim = "shag_loop_a", label = "Sexo ser activo", category = "New", loop = 0},
}

walkanims = {
	{dic = "amb@world_human_hang_out_street@female_arms_crossed@idle_a", anim = "idle_a", label = "Cruzarse de brazos"},
	{dic = "misscarsteal4@actor", anim = "actor_berating_assistant", label = "Que dices"},
}


scens = {
    {scen = "PROP_HUMAN_SEAT_ARMCHAIR", label = "Sentarse silla", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.55, -180}}},
    {scen = "WORLD_HUMAN_GUARD_STAND_ARMY", label = "Soldado", category = "Jobs"},
    {scen = "PROP_HUMAN_ATM", label = "ATM", category = "Misc"},
    {scen = "PROP_HUMAN_SEAT_BAR", label = "Sentarse bar", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.0, -0.3, 0}, ["mp_f_freemode_01"] = {0.0, 0.0, -0.2, 0}}},
    {scen = "PROP_HUMAN_BBQ", label = "BBQ", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_BENCH", label = "Sentarse banco", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_DRINK", label = "Banco beber", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_DRINK_BEER", label = "Banco beber cerveza", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_FOOD", label = "Comer en el banco", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS", label = "Banca pesas", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON", label = "Banca pesa(Prision)", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_BINOCULARS", label = "Prismaticos", category = "Misc"},
    {scen = "WORLD_HUMAN_WINDOW_SHOP_BROWSE", label = "Mirar por la ventana de la tienda", category = "Misc"},
    {scen = "PROP_HUMAN_SEAT_BUS_STOP_WAIT", label = "Parar Bus", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CAR_PARK_ATTENDANT", label = "Asistente de aparcamiento", category = "Jobs"},
    {scen = "PROP_HUMAN_SEAT_CHAIR", label = "Silla", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_DRINK", label = "Beber silla", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER", label = "Silla beber cerveza", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_FOOD", label = "Silla comer", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER", label = "Chair (MP Char)", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CHEERING", label = "Aplausos", category = "Misc"},
    {scen = "WORLD_HUMAN_CLIPBOARD", label = "Portapapeles", category = "Jobs"},
    {scen = "WORLD_HUMAN_AA_COFFEE", label = "Cafe", category = "Drink"},
    {scen = "CODE_HUMAN_POLICE_CROWD_CONTROL", label = "Control multitud", category = "EMS"},
    {scen = "PROP_HUMAN_SEAT_DECKCHAIR", label = "Tumbarse silla", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_DECKCHAIR_DRINK", label = "Tumbarse bebiendo", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CONST_DRILL", label = "Picar suelo", category = "Jobs"},
    {scen = "WORLD_HUMAN_DRINKING", label = "Beber", category = "Drink"},
    {scen = "WORLD_HUMAN_DRUG_DEALER", label = "Narcotraficante", category = "Jobs"},
    {scen = "WORLD_HUMAN_DRUG_DEALER_HARD", label = "Traficante de drogas duro", category = "Jobs"},
    {scen = "WORLD_HUMAN_MOBILE_FILM_SHOCKING", label = "Grabar con el telefono", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_FISHING", label = "Pescar", category = "Jobs"},
    {scen = "WORLD_HUMAN_MUSCLE_FLEX", label = "Flexionar", category = "Hobby"},
    {scen = "WORLD_HUMAN_BUM_FREEWAY", label = "Vagabundo", category = "Misc"},
    {scen = "WORLD_HUMAN_GUARD_PATROL", label = "Patrulla de la guardia", category = "Jobs"},
    {scen = "WORLD_HUMAN_GUARD_STAND", label = "Guardia de pie", category = "Jobs"},
    {scen = "WORLD_HUMAN_HAMMERING", label = "Martillar", category = "Jobs"},
    {scen = "WORLD_HUMAN_HANG_OUT_STREET", label = "Cruzarse de brazos", category = "Misc"},
    {scen = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS", label = "Prostituta de clase alta", category = "Jobs"},
    {scen = "WORLD_HUMAN_HIKER_STANDING", label = "Excursionista de pie", category = "Misc"},
    {scen = "WORLD_HUMAN_HUMAN_STATUE", label = "Estatua humana", category = "Jobs"},
    {scen = "WORLD_HUMAN_COP_IDLES", label = "Manos al cinturon", category = "Jobs"},
    {scen = "WORLD_HUMAN_STAND_IMPATIENT", label = "Impaciente", category = "Misc"},
    {scen = "WORLD_HUMAN_JANITOR", label = "Portero", category = "Jobs"},
    {scen = "WORLD_HUMAN_JOG_STANDING", label = "Trotar", category = "Misc"},
    {scen = "WORLD_HUMAN_GARDENER_LEAF_BLOWER", label = "Soplador de hojas", category = "Jobs"},
    {scen = "WORLD_HUMAN_LEANING", label = "Apoyarse", category = "Misc"},
    {scen = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", label = "Prostituta de clase baja", category = "Jobs"},
    {scen = "WORLD_HUMAN_VEHICLE_MECHANIC", label = "Mecanico", category = "Jobs"},
    {scen = "CODE_HUMAN_MEDIC_KNEEL", label = "Medico observar", category = "EMS"},
    {scen = "CODE_HUMAN_MEDIC_TIME_OF_DEATH", label = "Medico hora de la muerte", category = "EMS"},
    {scen = "WORLD_HUMAN_TOURIST_MOBILE", label = "Movil", category = "Misc"},
    {scen = "WORLD_HUMAN_MUSICIAN", label = "Musico", category = "Jobs"},
    {scen = "WORLD_HUMAN_PAPARAZZI", label = "Paparazzi", category = "Jobs"},
    {scen = "WORLD_HUMAN_PARTYING", label = "Fiesta", category = "Hobby"},
    {scen = "WORLD_HUMAN_PICNIC", label = "Picnic", category = "Hobby"},
    {scen = "WORLD_HUMAN_GARDENER_PLANT", label = "Plantar", category = "Jobs"},
    {scen = "CODE_HUMAN_POLICE_INVESTIGATE", label = "Policia investigacion", category = "EMS"},
    {scen = "WORLD_HUMAN_PUSH_UPS", label = "Flexiones", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_COMPUTER", label = "Sentado en el PC", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_UPRIGHT", label = "Sentarse vertical", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_SEWING", label = "Media vuelta", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_SECURITY_SHINE_TORCH", label = "Sacar linterna", category = "Jobs"},
    {scen = "WORLD_HUMAN_SIT_UPS", label = "Abdominales", category = "Hobby"},
    {scen = "WORLD_HUMAN_BUM_SLUMPED", label = "Desplomado", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_FIRE", label = "Nervioso", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_MOBILE", label = "Usar movil", category = "Misc"},
    {scen = "WORLD_HUMAN_BUM_STANDING", label = "Borracho", category = "Misc"},
    {scen = "WORLD_HUMAN_STUPOR", label = "Destruido", category = "Drink"},
    {scen = "WORLD_HUMAN_SUNBATHE", label = "Tomar el sol", category = "Hobby"},
    {scen = "WORLD_HUMAN_SUNBATHE_BACK", label = "Tomar el sol de espalda", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_SUNLOUNGER", label = "Tumbarse", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.8, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.9, -0.5, -180}}},
    {scen = "WORLD_HUMAN_SUPERHERO", label = "Superheroe", category = "Hobby"},
    {scen = "WORLD_HUMAN_SWIMMING", label = "Nadando", category = "Hobby"},
    {scen = "CODE_HUMAN_MEDIC_TEND_TO_DEAD", label = "Agachado", category = "EMS"},
    {scen = "WORLD_HUMAN_TENNIS_PLAYER", label = "Jugador tennis", category = "Hobby"},
    {scen = "WORLD_HUMAN_TOURIST_MAP", label = "Turista con mapa", category = "Misc"},
    {scen = "WORLD_HUMAN_BUM_WASH", label = "Buscar en el suelo", category = "Misc"},
    {scen = "WORLD_HUMAN_STRIP_WATCH_STAND", label = "Mirar Stripper", category = "Hobby"},
    {scen = "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS", label = "Pesas", category = "Hobby"},
    {scen = "WORLD_HUMAN_WELDING", label = "Soldadura", category = "Jobs"},
    {scen = "WORLD_HUMAN_YOGA", label = "Yoga", category = "Hobby"},
}

walks = {
    {Walk = "move_m@muscle@a", label = "Deprimido", category = "Walking"},
    {Walk = "move_m@business@a", label = "Empresario", category = "Walking"},
    {Walk = "move_m@brave@a", label = "Determinante", category = "Walking"},
    {Walk = "move_m@hipster@a", label = "Hipster", category = "Walking"},
    {Walk = "move_m@muscle@a", label = "Musculoso", category = "Walking"},
    {Walk = "move_m@shadyped@a", label = "Gordo", category = "Walking"},
    {Walk = "move_m@fat@a", label = "Chulo", category = "Walking"},
    {Walk = "move_f@sassy", label = "Descarado", category = "Walking"},
    {Walk = "move_m@injured", label = "Lesionado", category = "Walking"},
    {Walk = "move_m@money", label = "Orgulloso", category = "Walking"},
    {Walk = "move_f@arrogant@a", label = "Arrogante", category = "Walking"},
    {Walk = "anim@move_f@grooving@", label = "Paso de baile - Mujer", category = "Walking"},
    {Walk = "anim@move_f@grooving@", label = "Paso de baile 2 - Mujer", category = "Walking"},
    {Walk = "anim@move_m@grooving@", label = "Paso de baile - Hombre", category = "Walking"},
    {Walk = "anim@move_m@grooving@", label = "Paso de baile 2 - Hombre", category = "Walking"},
}

