function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
Citizen.CreateThread(function()
    AddTextEntry('eleanor', '67 Mustang GT500')
	AddTextEntry('MUSTGT19', '2019 Mustang GT')
	AddTextEntry('broncoc', '1975 Bronco')
	AddTextEntry('FGT', '2005 Ford GT')
	AddTextEntry('fairlane', '1965 Ford Mustang')
	AddTextEntry('SC427', '1965 Shelby Cobra')
	AddTextEntry('GT17','2017 Ford Mustang GT')
	AddTextEntry('mustang','1966 Mustang Hooniconr')
	AddTextEntry('MUDSLINGER','1980 Ford Bronco Mudslinger')
	AddTextEntry('2008f150','2008 Ford F150')
	AddTextEntry('F15078', '1978 Ford F150')
	AddTextEntry('19gt500','2020 Ford Shelby Mustang')
	--AddTextEntry('','')
	--AddTextEntry('','')
	--AddTextEntry('','')
	--AddTextEntry('','')
	--AddTextEntry('','')
	--AddTextEntry('','')
	--AddTextEntry('','')
    
end)