vehicles = {
 ["Casino"] = {
	 
 },
 ["Compacts"] = {
     {name = "Blista", price = 44000, model = "blista"},
     {name = "Brioso R/A", price = 24000, model = "brioso"},
     {name = "Dilettante", price = 16000, model = "Dilettante"},
     {name = "Issi", price = 40000, model = "issi2"},
     {name = "Panto", price = 30000, model = "panto"},
     {name = "Prairie", price = 34000, model = "prairie"},
     {name = "Escort MK1", price = 80000, model = "retinue"},  
     {name = "Sentinal Classic", price = 12000, model = "sentinel3"},
     {name = "Blista Compact", price = 48000, model = "blista2"},
     {name = "Blista Compact 2", price = 56000, model = "blista3"},
     {name = "Toyota Prius", price = 80000, model = "prius"},
 },
 ["Coupes"] = {
     {name = "Cognoscenti Cabrio", price = 300000, model = "cogcabrio"},
     {name = "Exemplar", price = 300000, model = "exemplar"},
     {name = "F620", price = 400000, model = "f620"},
     {name = "Felon", price = 140000, model = "felon"},
     {name = "Felon GT", price = 190000, model = "felon2"},
     {name = "Jackal", price = 80000, model = "jackal"},
     {name = "Oracle", price = 120000, model = "oracle"},
     {name = "Oracle XS", price = 150000, model = "oracle2"},
     {name = "Sentinel", price = 60000, model = "sentinel"},
     {name = "Sentinel XS", price = 60000, model = "sentinel2"},
     {name = "Zion", price = 110000, model = "zion"},
     {name = "Zion Cabrio", price = 150000, model = "zion2"},
 },
 ["Sedans"] = {
     {name="Asea", price = 40000, model="asea"},
     {name="Fugitive", price = 200000, model="fugitive"},
     {name="Asterope", price = 40000, model="asterope"},
     {name="Glendale", price = 30000, model="glendale"},
     {name="Ingot", price = 30000, model="ingot"},
     {name="Intruder", price = 30000, model="intruder"},
     {name="Premier", price = 30000, model="premier"},
     {name="Regina", price = 30000, model ="regina"},
     {name="Primo", price = 30000, model="primo"},
     {name="Schafter", price = 90000, model="schafter2"},
     {name="Tailgater", price = 80000, model="tailgater"},
     {name="Warrener", price = 80000, model="warrener"},
     {name="Washington", price = 80000, model="washington"},
     {name="Surge", price = 50000, model="surge"},
     {name="Super Diamond", price = 800000, model="superd"},
     {name="Stretch", price = 400000, model="stretch"},
     {name = "Golf MK7 GTI", price = 100000, model = "mk7"},
 },
 ["Muscle"] = {
     {name = "Blade", price = 50000, model = "blade"},
     {name = "Coquette BlackFin", price = 200000, model = "coquette3"},
     {name = "Dominator", price = 350000, model = "dominator"},
     {name = "Dominator 2018", price = 500000, model = "dominator2"},
     {name = "Gauntlet", price = 90000, model = "gauntlet"},
     {name = "Tampa", price = 150000, model = "tampa"},
     {name = "Vigero", price = 70000, model = "vigero"},
     {name = "Slam Van 2", price = 200000, model = "slamvan2"},
     {name = "Rat Loader", price = 50000, model = "ratloader"},
 },
 ["Offroads"] = {
     {name = "Bifta", price = 50000, model = "bifta"},
     {name = "Blazer", price = 40000, model = "blazer"},
     {name = "Brawler", price = 140000, model = "brawler"},
     {name = "Dune Buggy", price = 40000, model = "dune"},
     {name = "XLS", price = 120000, model = "xls"},
     {name = "Vapid Riata", price = 100000, model = "riata"},
 },
 ["SUV"] = {
     {name = "Baller", price = 350000, model = "baller"},
     {name = "Cavalcade", price = 40000, model = "cavalcade"},
     {name = "Granger", price = 150000, model = "granger"},
     {name = "Huntley S", price = 250000, model = "huntley"},
     {name = "Landstalker", price = 100000, model = "landstalker"},
     {name = "Radius", price = 30000, model = "radi"},
     {name = "Rocoto", price = 90000, model = "rocoto"},
     {name = "Seminole", price = 20000, model = "seminole"},
     {name = "Mesa", price = 100000, model = "mesa"},
 },
 ["Vans"] = {
     {name = "Bison", price = 60000, model = "bison"},
     {name = "Burrito", price = 30000, model = "burrito3"},
     {name = "Gansta Burrito", price = 39000, model = "gburrito2"},
     {name = "Camper", price = 40000, model = "camper"},
     {name = "Lost MC Burrito", price = 38000, model = "gburrito"},
     {name = "Journey", price = 15000, model = "journey"},
     {name = "Minivan", price = 28000, model = "minivan"},
     {name = "Paradise", price = 34000, model = "paradise"},
     {name = "Rumpo", price = 39000, model = "rumpo"},
     {name = "Rumpo Trail", price = 62000, model = "rumpo3"},
     {name = "Surfer", price = 120000, model = "surfer"},
     {name = "Youga", price = 24000, model = "youga"},
     {name = "Youga Luxuary", price = 24000, model = "youga2"},
     {name = "Bison 2", price = 60000, model = "bison2"},
     {name = "Bison 3", price = 60000, model = "bison3"},
 },
 ["Motorcycles"] = {
     {name = "Akuma", price = 14500, model = "AKUMA"},
     {name = "Defiler", price = 17000, model = "defiler"},
     {name = "PCJ-600", price = 15000, model = "pcj"},
     {name = "Vader", price = 120000, model = "vader"},
     {name = "Ruffian", price = 18000, model = "ruffian"},
     {name = "Hexer", price = 12000, model = "hexer"},
     {name = "Manchez", price = 90000, model = "manchez"},
     {name = "Enduro", price = 10000, model = "enduro"},
     {name = "Faggio", price = 6000, model = "faggio"},
     {name = "Vespa", price = 7000, model = "faggio2"},
     {name = "Rat Bike", price = 9000, model = "ratbike"},
	 {name = "Sanchez", price = 50000, model = "sanchez"},
 },
 ["Job Vehicles"] = {
     {name = 'Phantom', model = 'phantom', price = 500000},
     {name = 'Phantom 3', model = 'Phantom3', price = 700000},
     {name = 'Packer', model = 'packer', price = 550000},
     {name = 'Hauler', model = 'Hauler', price = 350000},
     {name = 'Taxi', model = 'taxi', price = 24000},
 },
}

